import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {GraphQLClient, gql} from 'graphql-request'

const inter = Inter({ subsets: ['latin'] })

const graphcms = new GraphQLClient('https://api-us-west-2.hygraph.com/v2/clbvxfsuy42y401usdso05d8l/master');



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>hi</h1>
      </main>
    </>
  )
}
